# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - uses: actions/cache@v4.0.2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore ./AppwriteConsole.App/AppwriteConsole.App.sln
    - name: Build
      run: dotnet build ./AppwriteConsole.App/AppwriteConsole.App.sln --no-restore
    - name: Test
      run: dotnet test ./AppwriteConsole.App/AppwriteConsole.App.sln --no-build --verbosity normal
    - name: Run Static Code Analysis
      run: dotnet tool install --global dotnet-format && dotnet format ./AppwriteConsole.App/AppwriteConsole.App.sln
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5.0.1
      with:
        commit_message: Apply code formatting
        commit_user_name: GitHub Actions
        commit_user_email: github-actions@github.com
        commit_author: GitHub Actions <github-actions@github.com>

        
